# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bc017a167faa299a9821d82028e0aa32"
name = "net-terms-tracker"
application_url = "https://net-terms-tracker-hjb.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_customers,read_orders,read_payment_customizations,read_themes,read_files,read_checkout_branding_settings,write_content,write_customers,write_orders,write_payment_customizations,write_products"

[auth]
redirect_urls = [
  "https://net-terms-tracker-hjb.fly.dev/auth/callback",
  "https://net-terms-tracker-hjb.fly.dev/auth/shopify/callback",
  "https://net-terms-tracker-hjb.fly.dev/api/auth/callback"
]

[app_proxy]
url = "https://net-terms-tracker-hjb.fly.dev/api/proxy"
subpath = "net-terms"
prefix = "apps"

