api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "net-terms-payment-rule"
type = "function"
uid = "b2f2cc20-a609-1a77-fb88-870ef74eeb03abf101a8"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.payment-methods.transform.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
